### ISSUE TITLE
[swm-gaps] gaps should not be applied to modeline

### ISSUE THREAD

**Issue by jamesmccabe** [stumpwm/stumpwm-contrib#100]
When I turn on swm-gaps it moves my modeline and adds gaps to it. 
I presume this should not be the default behavior and maybe it was only tested using Polybar instead of the Stump modeline?

Screenshot:
![2018-04-05-223601_1366x768_scrot](https://user-images.githubusercontent.com/6540118/38393333-632d5e1c-3922-11e8-9ea0-a635e8af320a.png)

Here is my [.stumpwmrc](https://github.com/jamesmccabe/dotfiles/blob/master/.stumpwmrc).

Removing `defun add-outer-gaps` function seems to fix the problem but the outergaps feature is lost.

**Comment by nipav** [comment]
I'm not the author of this module, but maybe this was intended? Although looking at the screenshot of the module, maybe not.

Perhaps there should be an option whether a user wants to apply gaps to the modeline or not. Thoughts?

**Comment by lepisma** [comment]
I am the author (for the outer gaps thing). I used polybar so didn't face this issue. I agree about having an option for applying gaps to modeline.

I think it might need some refactoring since the outer gaps were implemented by resizing the whole head. Allowing modeline might mean changing this.

**Comment by lepisma** [comment]
Another way might be to make the modeline aware of gaps and have it position itself correctly. Though I am not sure which way is going to be easier/better. Thoughts?

**Comment by jamesmccabe** [comment]
Thanks for the replies. My Lisp skills are poor so I don't know how easy it would be to implement the features. My guess is not very easy 😁. If we could just make the modeline stay in default position I would be happy with that. 

Having the option to apply gaps to the modeline or turning it off would be cool though. 
Applying gaps to the modeline could be another module maybe with separate code? I'm not sure if that would work either.

**Comment by lepisma** [comment]
I will give it a shot this weekend.

**Comment by lepisma** [comment]
I have a possible fix in [here](https://github.com/lepisma/stumpwm-contrib/tree/patch-outer-gaps). There are now three _kind_ of gaps defined by the following variables:

1. `*head-gaps-size*`. This is what borders the monitor. Everything (including modeline) comes inside its boundary. You would want to set it to 0.
2. `*outer-gaps-size*` mimicks the behaviour of the older variable with same name but adds asymmetric gaps around individual windows after checking if they are facing monitor edges.
3. `*inner-gaps-size*` is the same old thing.

Here is a quick picture to describe these.

![screenshot_20180429_181105 png](https://user-images.githubusercontent.com/2487306/39411840-1da9e06c-4c01-11e8-86df-96df3c83d3e8.png)

The outermost gaps are due to `*head-gaps-size*`. The innermost (around all edges of window) are due to `*inner-gaps-size*` and the extra gaps for the monitor facing edges is from `*outer-gaps-size*`.

Try the fork and see if it behaves correctly. If all looks fine, then I will create a PR here.

**Comment by jamesmccabe** [comment]
Thanks Abhinav it seems to work fine. I am getting an error message though which doesn't effect the functionality though.

> Error in command 'toggle-gaps': The function STUMPWM:ONLY-TILE-WINDOW is undefined.

Maybe I am doing something wrong?

![2018-05-01-001919_1366x768_scrot](https://user-images.githubusercontent.com/6540118/39454895-b16d741a-4cd5-11e8-8500-331ad4df851c.png)

**Comment by nipav** [comment]
I'm looking at the code right now. Are you using the latest version of the fork, @jamesmccabe ? Your `reset-all-windows` function looks different (looks like commit `08918d7`).

**Comment by nipav** [comment]
I just tried it myself. Seems to work fine. @lepisma 

How are you getting that error? @jamesmccabe

**Comment by lepisma** [comment]
Which version of stumpwm are you using @jamesmccabe? (although the missing function is [around a year old](https://github.com/stumpwm/stumpwm/blame/2a971b8564131493a5ae0169ecf82adc5e80a0be/tile-window.lisp#L208) so don't know if this matters).

**Comment by jamesmccabe** [comment]
Sorry I am using stumpwm version 1.0.0 so I think this is the problem. I will test the git version later.

**Comment by lepisma** [comment]
Right, I now realize that v1 doesn't have that fn. Since, v1 is latest stable release, should I revert the change that I made (https://github.com/lepisma/stumpwm-contrib/commit/08918d79fb33c20a04b86e5ac99f37f573c5a52f)? I think addon modules should at least work with the latest stable.

**Comment by lepisma** [comment]
Or I can also take this opportunity to ask @dbjergaard if `v1.0.1-rc` can go as a stable release? I feel there are sufficient amount of _really_ useful changes in the `rc`. Its also been working without any hiccups for me at least. How are others feeling about it?

**Comment by nipav** [comment]
Maybe you should have a look at this: stumpwm/stumpwm#454, @lepisma.
