### ISSUE TITLE
Guide on how to add contrib modules to stumpwm after refactoring

### ISSUE THREAD

**Issue by christianlask** [stumpwm/stumpwm-contrib#17]
Hello there!

I am currently using the `0.9.8` of `stumpwm`. I packaged it for `NixOS` (not yet commited). I tried to package current `master`, too, but failed to do it. `stumpwm` works, but fails to load modules. The `*contrib-dir*` is set properly, but that ain't enough/the right thing to do anymore, apparently. 

The error message I get as soon as I am trying to load a module via `(load-module ...)` tells me something about a missing `package.lisp` and `TRUENAME` in a path in `tmp`. 

I am not familiar enough with Common Lisp to help myself. Especially, `asdf`is completely unknown to me. Maybe a guide on how to work with the contrib modules after the split would help a lot.

**Comment by dbjergaard** [comment]
@23a1a74 I tried playing with this a while back and I can't reproduce your issue, have you seen any progress on your end? It would be great if you could distill npm's package build process into a shell script or some shell code that I could run on my system.

Dave

**Comment by 23a1a74** [comment]
@dbjergaard 

Same here. I am sorry I neglected this issue for so long. :(

I did not, however, forget all about it. I am in active discussion with a co-worker who also uses `stumpwm` on `NixOS` and who thus should have the same problems I am experiencing. He might help me in better understanding what is going wrong. I come back at this as soon as we both found the time to investigate.

**Comment by dbjergaard** [comment]
Just checking in on this issue, did you ever get it resolved?

**Comment by dbjergaard** [comment]
Thinking outloud: 
It appears the issue is more with asdf and some variable getting set during compile time and not during runtime.  This causes your error, and for any use case where compile time and run time are the same directory, there is no error.

The "new" way of handling stumpwm for a package maintainer should be:
1. build/package stumpwm
2. package stumpwm-contrib
3. tell stumpwm where to pick up the modules packaged in 2

I just recently got bit by something like this switching to debian from ubuntu.  I had to regenerate my makefile from scratch and everything worked as expected.  Can you confirm this problem exists if you start completely fresh?

**Comment by 1126** [comment]
@dbjergaard I am sorry, again it took me way too long to respond. I was sick and busy and all. Well, the issue is still alive, but I managed to get friends to look at it, too. I failed. I keep you posted as soon as they achieve something.

It might just be the combination of `asdf` and `NixOS` that's not as easy as one might wish. Hm.

**Comment by jqtruong** [comment]
@hiberno i'm running into the same problem with `asdf` looking in the `/tmp` directory for `stumpwm`'s `package.lisp`. Can you tell me how you stopped `asdf` from reloading the modules?

**Comment by hiberno** [comment]
@jqtruong I didn't fix that issue myself. The fix a colleague proposed was specific for the [NixOS](https://nixos.org/) package of `stumpwm`. The fixing commit can be reviewed [here](https://github.com/NixOS/nixpkgs/commit/4eaf2f1114e3119e3f4f20a72b63e1cf6a361c0d).

What OS are you running `stumpwm` on?

**Comment by jorams** [comment]
I just opened stumpwm/stumpwm#283 which should fix this issue more generally.
