### ISSUE TITLE
stumpwm-dmenu stops loading with error (xEMBED)

### ISSUE THREAD

**Issue by spiderbit** [stumpwm/stumpwm-contrib#261]
I have the community package of stumpwm installed and when try to load the dmenu module with (load-module "dmenu") and try to load the config I get the error:

> 
Component #:xEMBED not found. required by #<System "dmenu">

**Comment by Sasanidas** [comment]
Hello, stumpwm-dmenu mantainer here, sorry that I didn't saw the issue, given that it's a third party ,I have a separate [issues](https://gitlab.com/sasanidas/stumpwm-dmenu/-/issues) in gitlab.
In any case, you are right! There is a dependency on [xembed](https://github.com/laynor/clx-xembed) that is not in use.

Fixed in master, the package now only depends on alexandria and stumpwm
