### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by cwebber** [stumpwm/stumpwm-contrib#44]
This project doesn't have a COPYING file or any license notification, so I'm really not sure what license things are under... remember that the default copyright status is "all rights reserved", which is surely not what stumpwm contributors want!

**Comment by dbjergaard** [comment]
The old contrib modules were shipped with StumpWM so its license (GPL2) applies.  A few new ones have been added via PR, so I'll have to contact those authors and ask for GPL2 permission.

**Comment by dbjergaard** [comment]
In fact: ```grep "license" $(find . -name "*.asd")``` answers this debate.  I'll add a LICENSE file that refers people who are curious to the asd files since those specify the licenses of the individual modules (they're all GPLv3 except hostname which is 2-CLAUSE BSD and a couple that are unspecified).  I wrote numpad-layouts so I can change that license, and I ported mpd from the original stumpwm contrib dir, so that should also be GPLv2.
